on: pull_request

# Sets permissions of the GITHUB_TOKEN to allow write pull-requests
permissions:
  pull-requests: write

jobs:
  delta-typescript-graph-job:
    runs-on: ubuntu-latest
    name: Test with params
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Delta Typescript Graph
        id: tsg
        uses: ysk8hori/delta-typescript-graph-action@fd6736245b0bc12685a8d40db6d5a8b5dcf27408
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          tsconfig-root: './src'
          max-size: 3
          orientation: LR
          debug: true
          in-details: true
          exclude: 'test'
          include-index-file-dependencies: true
