on: pull_request

# Sets permissions of the GITHUB_TOKEN to allow write pull-requests
permissions:
  pull-requests: write

jobs:
  delta-typescript-graph-job:
    runs-on: ubuntu-latest
    name: Test with params
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - name: Delta Typescript Graph
        id: tsg
        uses: ysk8hori/delta-typescript-graph-action@1a7a61fc86151cacbc968d7af271c3a229b97d05
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          tsconfig-root: './src'
          max-size: 3
          orientation: LR
          debug: true
          in-details: true
          exclude: 'test'
          include-index-file-dependencies: true
