on: pull_request

# Sets permissions of the GITHUB_TOKEN to allow write pull-requests
permissions:
  pull-requests: write

jobs:
  delta-typescript-graph-job:
    runs-on: ubuntu-latest
    name: Test with params
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Delta Typescript Graph
        id: tsg
        uses: ysk8hori/delta-typescript-graph-action@79d3037357a9f971e7787fab3700c11d2c1d2f83
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          tsconfig-root: './src'
          max-size: 3
          orientation: LR
          debug: true
          in-details: true
          exclude: 'test'
          include-index-file-dependencies: true
